site_name: "Hacking Archive"
site_description: "Various writeups and guides for Hack The Box machines and challenges."
theme:
  name: material
  language: en
  custom_dir: overrides
  font:
    code: Fira Code
  palette:
    - scheme: slate
      primary: blue grey
      accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

plugins:
  - search

copyright: >
  Made with ❤️ by <a href="https://github.com/egz-dev" target="_blank" rel="noopener">egz-dev</a> — 
  <a href="https://edugarcia.dev" target="_blank" rel="noopener">edugarcia.dev</a>

# --nav-auto-start--
nav:
  - Home: index.md
  - Writeups:
      - writeups/index.md
      - Very Easy:
          - 🐊 Crocodile: writeups/🐊 Crocodile.md
          - 🐬 Sequel: writeups/🐬 Sequel.md
          - 👹 Mongod: writeups/👹 Mongod.md
          - 💥 Explosion: writeups/💥 Explosion.md
          - 💾 Redeemer: writeups/💾 Redeemer.md
          - 📅 Appointment: writeups/📅 Appointment.md
          - 🔄 Synced: writeups/🔄 Synced.md
          - 🦌 Fawn: writeups/🦌 Fawn.md
          - 🧑‍🚒 Responder: writeups/🧑‍🚒 Responder.md
          - 🧨 Preignition: writeups/🧨 Preignition.md
          - 🩰 Dancing: writeups/🩰 Dancing.md
  - Guides:
      - guides/index.md
      - ✅ Checklist Ctf: guides/✅ Checklist CTF.md
      - 🍃 Mongodb: guides/🍃 MongoDB.md
      - 🐬 Mysql: guides/🐬 MySQL.md
      - 💉 Lfi & Rfi: guides/💉 LFI & RFI.md
      - 💉 Sql Injection: guides/💉 SQL Injection.md
      - 💣 Gobuster: guides/💣 Gobuster.md
      - 📂 Smb: guides/📂 SMB.md
      - 🔄 Rsync: guides/🔄 Rsync.md
      - 🔐 Ntlm: guides/🔐 NTLM.md
      - 🔧 John The Ripper: guides/🔧 John the Ripper.md
      - 🖥️ Winrm: guides/🖥️ WinRM.md
      - 🖥️ Xfreerdp: guides/🖥️ xfreerdp.md
      - 🗃️ Ftp: guides/🗃️ FTP.md
      - 🗄️ Redis: guides/🗄️ Redis.md
      - 🗺️ Nmap: guides/🗺️ Nmap.md
# --nav-auto-end--
